In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('C:/Users/Asus/Downloads/Final_Train_Test.csv',low_memory=False)
df

,Provider,PotentialFraud,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,...,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt
0,PRV51001,No,BENE36012,CLM58316,2009-07-04,2009-07-08,36000,PHY340163,NaN,NaN,...,1,1,1,2,2,1,36000,1068,3520,140
1,PRV51001,No,BENE38773,CLM52334,2009-05-23,2009-05-25,12000,PHY346762,NaN,NaN,...,2,2,2,2,2,2,95000,2136,2270,900
2,PRV51001,No,BENE98831,CLM36844,2009-02-03,2009-02-08,3000,PHY383193,NaN,NaN,...,1,1,1,2,1,2,3000,1068,0,0
3,PRV51001,No,BENE102690,CLM49733,2009-05-04,2009-05-18,42000,PHY383193,PHY378091,PHY389113,...,1,1,1,2,1,2,143800,4272,880,70
4,PRV51001,No,BENE152088,CLM37205,2009-02-06,2009-02-06,4000,PHY402229,PHY329739,NaN,...,1,1,1,2,1,1,111710,4272,80,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
693598,PRV57750,NaN,BENE142702,CLM672301,2009-11-08,2009-11-09,1300,PHY323525,NaN,NaN,...,1,1,1,2,2,2,0,0,2300,60
693599,PRV57750,NaN,BENE143805,CLM603938,2009-09-28,2009-09-28,10,PHY374125,NaN,NaN,...,1,2,1,2,2,2,0,0,2970,760
693600,PRV57750,NaN,BENE146568,CLM236733,2009-03-09,2009-03-09,200,PHY323525,NaN,NaN,...,1,2,1,2,2,2,0,0,200,60
693601,PRV57750,NaN,BENE148715,CLM624293,2009-10-10,2009-10-12,2300,PHY323525,PHY323525,NaN,...,2,1,1,2,2,2,0,0,5640,830
693602,PRV57750,NaN,BENE150236,CLM675578,2009-11-10,2009-11-10,200,PHY323525,PHY323525,PHY323525,...,2,2,1,2,2,2,0,0,290,1120

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 693603 entries, 0 to 693602
Data columns (total 55 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Provider                         693603 non-null  object
 1   PotentialFraud                   558211 non-null  object
 2   BeneID                           693603 non-null  object
 3   ClaimID                          693603 non-null  object
 4   ClaimStartDt                     693603 non-null  object
 5   ClaimEndDt                       693603 non-null  object
 6   InscClaimAmtReimbursed           693603 non-null  int64
 7   AttendingPhysician               691748 non-null  object
 8   OperatingPhysician               141640 non-null  object
 9   OtherPhysician                   248368 non-null  object
 10  AdmissionDt                      50025 non-null   object
 11  ClmAdmitDiagnosisCode            181255 non-null  object
 12  DeductibleAmtPaid                692508 non-null  float64
 13  DischargeDt                      50025 non-null   object
 14  DiagnosisGroupCode               50025 non-null   object
 15  ClmDiagnosisCode_1               680572 non-null  object
 16  ClmDiagnosisCode_2               450212 non-null  object
 17  ClmDiagnosisCode_3               301703 non-null  object
 18  ClmDiagnosisCode_4               204153 non-null  object
 19  ClmDiagnosisCode_5               138722 non-null  object
 20  ClmDiagnosisCode_6               104552 non-null  object
 21  ClmDiagnosisCode_7               81962 non-null   object
 22  ClmDiagnosisCode_8               66166 non-null   object
 23  ClmDiagnosisCode_9               51691 non-null   object
 24  ClmDiagnosisCode_10              6160 non-null    object
 25  ClmProcedureCode_1               28777 non-null   float64
 26  ClmProcedureCode_2               6753 non-null    float64
 27  ClmProcedureCode_3               1194 non-null    float64
 28  ClmProcedureCode_4               147 non-null     float64
 29  ClmProcedureCode_5               11 non-null      float64
 30  ClmProcedureCode_6               0 non-null       float64
 31  DOB                              693603 non-null  object
 32  DOD                              5171 non-null    object
 33  Gender                           693603 non-null  int64
 34  Race                             693603 non-null  int64
 35  RenalDiseaseIndicator            693603 non-null  object
 36  State                            693603 non-null  int64
 37  County                           693603 non-null  int64
 38  NoOfMonths_PartACov              693603 non-null  int64
 39  NoOfMonths_PartBCov              693603 non-null  int64
 40  ChronicCond_Alzheimer            693603 non-null  int64
 41  ChronicCond_Heartfailure         693603 non-null  int64
 42  ChronicCond_KidneyDisease        693603 non-null  int64
 43  ChronicCond_Cancer               693603 non-null  int64
 44  ChronicCond_ObstrPulmonary       693603 non-null  int64
 45  ChronicCond_Depression           693603 non-null  int64
 46  ChronicCond_Diabetes             693603 non-null  int64
 47  ChronicCond_IschemicHeart        693603 non-null  int64
 48  ChronicCond_Osteoporasis         693603 non-null  int64
 49  ChronicCond_rheumatoidarthritis  693603 non-null  int64
 50  ChronicCond_stroke               693603 non-null  int64
 51  IPAnnualReimbursementAmt         693603 non-null  int64
 52  IPAnnualDeductibleAmt            693603 non-null  int64
 53  OPAnnualReimbursementAmt         693603 non-null  int64
 54  OPAnnualDeductibleAmt            693603 non-null  int64
dtypes: float64(7), int64(22), object(26)
memory usage: 291.0+ MB

In [4]:
df.isna().sum()

Provider                                0
PotentialFraud                     135392
BeneID                                  0
ClaimID                                 0
ClaimStartDt                            0
ClaimEndDt                              0
InscClaimAmtReimbursed                  0
AttendingPhysician                   1855
OperatingPhysician                 551963
OtherPhysician                     445235
AdmissionDt                        643578
ClmAdmitDiagnosisCode              512348
DeductibleAmtPaid                    1095
DischargeDt                        643578
DiagnosisGroupCode                 643578
ClmDiagnosisCode_1                  13031
ClmDiagnosisCode_2                 243391
ClmDiagnosisCode_3                 391900
ClmDiagnosisCode_4                 489450
ClmDiagnosisCode_5                 554881
ClmDiagnosisCode_6                 589051
ClmDiagnosisCode_7                 611641
ClmDiagnosisCode_8                 627437
ClmDiagnosisCode_9                 641912
ClmDiagnosisCode_10                687443
ClmProcedureCode_1                 664826
ClmProcedureCode_2                 686850
ClmProcedureCode_3                 692409
ClmProcedureCode_4                 693456
ClmProcedureCode_5                 693592
ClmProcedureCode_6                 693603
DOB                                     0
DOD                                688432
Gender                                  0
Race                                    0
RenalDiseaseIndicator                   0
State                                   0
County                                  0
NoOfMonths_PartACov                     0
NoOfMonths_PartBCov                     0
ChronicCond_Alzheimer                   0
ChronicCond_Heartfailure                0
ChronicCond_KidneyDisease               0
ChronicCond_Cancer                      0
ChronicCond_ObstrPulmonary              0
ChronicCond_Depression                  0
ChronicCond_Diabetes                    0
ChronicCond_IschemicHeart               0
ChronicCond_Osteoporasis                0
ChronicCond_rheumatoidarthritis         0
ChronicCond_stroke                      0
IPAnnualReimbursementAmt                0
IPAnnualDeductibleAmt                   0
OPAnnualReimbursementAmt                0
OPAnnualDeductibleAmt                   0
dtype: int64

# Applying basic column transformation

In [5]:
#Replacing 2 with 0 for chronic conditions, 0 indicates no chronic condition , 1 -> yes for chronic conditions
df=df.replace({'ChronicCond_Alzheimer': 2, 'ChronicCond_Heartfailure': 2, 'ChronicCond_KidneyDisease': 2,
                           'ChronicCond_Cancer': 2, 'ChronicCond_ObstrPulmonary': 2, 'ChronicCond_Depression': 2,
                           'ChronicCond_Diabetes': 2, 'ChronicCond_IschemicHeart': 2, 'ChronicCond_Osteoporasis': 2,
                           'ChronicCond_rheumatoidarthritis': 2, 'ChronicCond_stroke': 2 }, 0)

In [6]:
df[['ChronicCond_Alzheimer','ChronicCond_Heartfailure']]

        ChronicCond_Alzheimer  ChronicCond_Heartfailure
0                           0                         1
1                           0                         0
2                           1                         1
3                           0                         1
4                           1                         1
...                       ...                       ...
693598                      0                         1
693599                      0                         0
693600                      0                         0
693601                      1                         0
693602                      0                         1

[693603 rows x 2 columns]

In [7]:
#0->male,1->female
df=df.replace({'Gender':2},0)

In [8]:
#0->no , 1-> yes
df=df.replace({'RenalDiseaseIndicator':'Y'},1)

In [9]:
df.RenalDiseaseIndicator

0         0
1         0
2         0
3         1
4         1
         ..
693598    0
693599    0
693600    0
693601    0
693602    0
Name: RenalDiseaseIndicator, Length: 693603, dtype: object

In [10]:
df.PotentialFraud.value_counts()

PotentialFraud
No     345415
Yes    212796
Name: count, dtype: int64

In [12]:
# Replace 'Yes'/'No' with 1/0 and ensure integer type
# Replace 'Yes'/'No' with 1/0
df['PotentialFraud'] = df['PotentialFraud'].map({'Yes': 1, 'No': 0})

# Fill missing values (if any) with 0 or your desired default
df['PotentialFraud'] = df['PotentialFraud'].fillna(0).astype(int)

In [13]:
df.PotentialFraud.value_counts()

PotentialFraud
0    480807
1    212796
Name: count, dtype: int64